name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      matrix:
        spark_version: ["3.0.1", "3.1.1", "3.2.1", "3.3.1", "3.4.1", "3.5.1"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build and Test
      run:   sbt  -DsparkVersion=${{ matrix.spark_version }} version clean test
